Develop
hanz0m4/microservice pull request #2
Opened 2024-04-08 19:00 UTC by hanz0m4

2024-04-16 17:17 UTC, vladefr97 requested changes

2024-04-16 17:17 UTC, vladefr97 commented on Task#1.py
> +
Лишние отступы

2024-04-16 17:17 UTC, vladefr97 commented on Task#3.py
> +class figure:
В Питоне классы называются с большой буквы в CamelCase

2024-04-16 17:17 UTC, vladefr97 commented on Task#3.py
> +    def sravnenie_per(self, other):
Нужно давать все названия на английском

2024-04-16 17:17 UTC, vladefr97 commented on Task#3.py
> +            return "больше"
Логичение возвращать результаты сравнения True/False

2024-04-16 17:17 UTC, vladefr97 commented on Task#3.py
> +            return "меньше"
Избегай строковых литералов

2024-04-16 17:17 UTC, vladefr97 commented on Task#4.py
> +            return 6000
Числовых литералов тоже избегай, выноси все в константы.
Советую почитать: https://mgorbatyuk.dev/blog/books/2019-09-19-clean-code/

2024-04-29 20:23 UTC, hanz0m4 commented on Task#1.py
> +
Внёс изменения

2024-04-29 20:24 UTC, hanz0m4 commented on Task#3.py
> +class figure:
Внёс изменения

2024-04-29 20:24 UTC, hanz0m4 commented on Task#3.py
> +    def sravnenie_per(self, other):
Внёс правки в код

2024-04-29 20:24 UTC, hanz0m4 commented on Task#3.py
> +            return "больше"
Окей, исправил

2024-04-29 20:25 UTC, hanz0m4 commented on Task#3.py
> +            return "меньше"
Хорошо, исправил

2024-04-29 20:25 UTC, hanz0m4 commented on Task#4.py
> +            return 6000
Исправил

2024-05-01 11:34 UTC, vladefr97 approved these changes

2024-05-01 11:34 UTC, vladefr97 commented on Task#3.py
> +
Проблемы с отступами остались

2024-05-13 13:16 UTC, merged